import type { Metadata } from "next";
import {
  Cormorant_Garamond,
  Geist_Mono,
  Marck_Script,
  Spectral,
} from "next/font/google";
import "./globals.css";

const spectral = Spectral({
  variable: "--font-body",
  subsets: ["cyrillic", "latin"],
  weight: ["400", "500", "600", "700"],
});

const cormorantGaramond = Cormorant_Garamond({
  variable: "--font-display",
  subsets: ["cyrillic", "latin"],
  weight: ["400", "500", "600", "700"],
});

const marckScript = Marck_Script({
  variable: "--font-signature-source",
  subsets: ["cyrillic", "latin"],
  weight: "400",
});

const geistMono = Geist_Mono({
  variable: "--font-code",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ru"
      className={`${spectral.variable} ${cormorantGaramond.variable} ${marckScript.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="theme-dark min-h-full flex flex-col">{children}</body>
    </html>
  );
}
